pladuch_login_sga:
  pattern:     /gestion/login
  defaults: { _controller: PladuchBackBundle:Login:login }

pladuch_login_check:
  pattern:     /gestion/login_check

pladuch_logout_sga:
  pattern:  /gestion/logout

pladuch_sga_index:
  pattern:  /gestion/index
  defaults: { _controller: PladuchBackBundle:Sga:index }
